### ISSUE TITLE
How can we list all permissions on a resource?

### ISSUE THREAD

**Issue by luanxuechao** [authzed/authzed-node#125]
```
curl --location 'http://localhost:8443/v1/permissions/expand' \
--data '{
    "consistency": {
        "minimizeLatency": true
    },
    "resource": {
        "objectType": "document",
        "objectId": "topsecret1"
    },
    "permission": "view"
}'
```
We need to add permission when we expand the permission on the resource, can we expand without permission or write it as `*`?

**Comment by luanxuechao** [comment]
Hi @josephschorr, do you know it?

**Comment by luanxuechao** [comment]
Hi @josephschorr, I use the LoopupSubjects to do it,
```
onst request = v1.LookupSubjectsRequest.create({
  resource: v1.ObjectReference.create({
    objectType: `${systemPrefix}/${referenceType}`,
    objectId: referenceId
  }),
  subjectObjectType: 'meta_permission/user',
  permission: 'can_view',
  consistency: v1.Consistency.create({
    requirement: {
      oneofKind: 'minimizeLatency',
      minimizeLatency: true
    }
  }),
  context: Struct.fromJson({ })
});
```
but it always return error:
```
Error: 14 UNAVAILABLE: Connection dropped
```
Do you know it?

**Comment by vroldanbet** [comment]
You cannot list permissions on a resource. `LookupResources` gives you the list of resources over which the user has _a specific permission_. Those are two different things.

To determine the permissions defined on a resource, you use the reflection API. Once you've determined the permissions available on a resource type, then you go and check that on a single resource (`CheckPermission`) or to obtain the list of resources with that specific permission for a subject (`LookupResources`).

>Error: 14 UNAVAILABLE: Connection dropped

I don't think I've seen that before. Can you provide more information about your setup?
We have some examples on how to do `LookupResources` [here](https://github.com/authzed/authzed-node/blob/main/src/v1-promise.test.ts#L407-L417)

We recommend using GitHub Discussions or our Discord channel for these kind of questions.

**Comment by luanxuechao** [comment]
Yeah, I sent it on the Discord
