### ISSUE TITLE
bug: doesn't work with @grpc/grpc-js 1.12.0 version

### ISSUE THREAD

**Issue by karlismelderis-mckinsey** [authzed/authzed-node#166]
Latest @grpc/grpc-js 1.12.0 version doesn't work with autzed client

we're getting this error message:
```
"14 UNAVAILABLE: No connection established. Last error: Credentials not loaded"
```

wouldn't be surprised if breaking change is on @grpc/grpc-js side as it's only minor version release 🤷

**Comment by malosayli** [comment]
I encounter the same issue with self-hosted spicedb. @karlismelderis-mckinsey Did you manage to solve it?

**Comment by malosayli** [comment]
@karlismelderis-mckinsey I managed to solve this issue by overriding the version of `@grpc/grpc-js` used by authzed to use `1.11.3`. Here's how I did it:

In the package.json file, I added an "overrides" section at the root level.
In this section, I specified the version of @grpc/grpc-js to use:
```json
{
  "overrides": {
    "@grpc/grpc-js": "1.11.3"
  }
}
```

**Comment by tstirrat15** [comment]
I'm at an offsite right now but I'll check this when i get a chance. Thanks for the heads-up!

**Comment by tstirrat15** [comment]
I've gotten reports that v1.0.3 fixes the observed issue. I'm going to close this for now; if the issue resurfaces please comment here and I can reopen.
