### ISSUE TITLE
Incorrect typing for some optional attributes

### ISSUE THREAD

**Issue by williamdclt** [authzed/authzed-node#27]
Some of the attributes in types exported by the client are incorrectly typed: they are required when they are supposed to be optional.

For example, the `RelationshipFilter`:
```ts
/**
 * RelationshipFilter is a collection of filters which when applied to a
 * relationship will return relationships that have exactly matching fields.
 *
 * resource_type is required. All other fields are optional and if left
 * unspecified will not filter relationships.
 *
 * @generated from protobuf message authzed.api.v1.RelationshipFilter
 */
export interface RelationshipFilter {
    /**
     * @generated from protobuf field: string resource_type = 1;
     */
    resourceType: string;
    /**
     * @generated from protobuf field: string optional_resource_id = 2;
     */
    optionalResourceId: string;
    /**
     * @generated from protobuf field: string optional_relation = 3;
     */
    optionalRelation: string;
    /**
     * @generated from protobuf field: authzed.api.v1.SubjectFilter optional_subject_filter = 4;
     */
    optionalSubjectFilter?: SubjectFilter;
}
```

From the docstring and the name of the attributes, `optionalResourceId` and `optionalRelation` are clearly supposed to be optional, but here they are required in the type declaration.

Note that `optionalSubjectFilter` is correctly typed as optional: maybe the proto->TS translator doesn't handle scalar-ish types (eg strings) the same way as objects?

**Comment by josephschorr** [comment]
> maybe the proto->TS translator doesn't handle scalar-ish types (eg strings) the same way as objects?

This is likely the reason, yeah. Technically the other optionals are still required to be empty string.

I think using `.create` might handle it automatically, but will need to confirm

**Comment by samkim** [comment]
It's the way `repeated` fields are handled by the translator and the use of the `.create` helpers is the recommended approach. More info in this comment on a similar issue: https://github.com/authzed/authzed-node/issues/33#issuecomment-1229068258
