### ISSUE TITLE
Expose grpc-js options

### ISSUE THREAD

**Issue by svenefftinge** [authzed/authzed-node#62]
When creating a client through `v1.NewClient`it would be great to allow providing `grpc-js` options (i.e. [channel-options](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/channel-options.ts#L23)) to conmfigure e.g. the underlying channel.

**Comment by samkim** [comment]
Believe this is doable currently by setting the options param:
https://github.com/authzed/authzed-node/blob/main/src/v1.ts#L293

Partial ChannelOptions can be included with this arg:
https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/client.ts#L100

@svenefftinge does this accomplish what you're looking for?

**Comment by svenefftinge** [comment]
Oh, yes. Sorry I was not checking the latest version. 😬
