### ISSUE TITLE
Consider dropping (yarn) lockfile

### ISSUE THREAD

**Issue by edorivai** [authzed/authzed-node#72]
From [_When Not to Use Lock Files with Node.js_](https://www.twilio.com/blog/lockfiles-nodejs) (twilio)...

> Lock files are super useful if you build an application like a web server. However, if you publish a library or CLI to npm, lock files are never published. Meaning your users and you might use different versions of dependencies if you use lock files. 

And given [this recent report](https://github.com/authzed/authzed-node/issues/64) - it might be a good idea to drop internal usage of lockfiles, so that there's a better chance of catching bugs due to later versions of transitive dependencies.

**Comment by tstirrat15** [comment]
We went ahead and did this in #168. We'll also probably do it in authzed-py at some point. I appreciate you bringing it up!
