### ISSUE TITLE
Question: How to access StreamingBulkCheckPermission?

### ISSUE THREAD

**Issue by Niral221b** [authzed/authzed-node#82]
While I was going through the experimental service, I stumbled upon this StreamingBulkCheckPermission method and wanted to know if this accessible and if so how can we do that? Any examples would help.

Also from what I understood, all the methods supports promises and wait for the stream to close to collect the data. If there any way to possibly collect the stream data as it is?

Any info would be helpful to understand.
Thank you

**Comment by josephschorr** [comment]
`StreamingBulkCheckPermission` is a relict of an earlier experimental idea and was never implemented. We'll make sure to update the API reference to remove it.
